"""Declarative base and the shared timestamp columns.

**Reconstructed 2026-09-07.** This file, along with `chat.py`,
`document.py` and `upload_job.py`, was never committed: `.gitignore`
carried an unanchored `models/` rule (intended for downloaded ML
weights) which matched `backend/app/models/` too. `__init__.py` survived
only because it had been committed before that rule was added, and
`.gitignore` does not affect already-tracked files — which is why
`git status` never reported the others as untracked, and why a fresh
clone of this repository could not start.

Rebuilt against `migrations/versions/20260901_0001_initial_schema.py`,
which is the authoritative description of the schema. If you change a
column here, change it there too — `alembic check` is what will tell
you if they have drifted.
"""

from datetime import datetime

from sqlalchemy import DateTime, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Declarative base for every ORM model.

    `__tablename__` is set explicitly on each model rather than derived
    from the class name: the table names are already fixed by migration
    0001, and deriving them would make a class rename silently a schema
    change.
    """


class TimestampMixin:
    """`created_at` / `updated_at` on every table.

    Both are `TIMESTAMPTZ NOT NULL DEFAULT now()`, generated by
    PostgreSQL rather than by Python. That matters for `created_at`: a
    value produced by the application would carry the app server's clock
    and timezone, so two backends with different settings would write
    inconsistent history into one table.

    `updated_at` additionally has `onupdate`, which SQLAlchemy applies
    as part of the UPDATE statement. It is not part of the DDL, so it
    does not appear in the migration and `alembic check` sees no
    difference.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
